### ISSUE TITLE
Highlight key value pairs differently

### ISSUE THREAD

**Issue by balavishnuvj** [kettanaito/vscode-nako-theme#5]
<img width="256" alt="Screenshot 2020-09-23 at 7 14 54 PM" src="https://user-images.githubusercontent.com/13718688/94021941-32796f00-fdd2-11ea-8771-4c83a81bb55f.png">

**Comment by kettanaito** [comment]
Hi, @balavishnuvj. Thanks for suggesting this.

Could you tell me more when does such coloring occur? When I use a similar code in Nako it highlights keys and values of object arguments differently:

<img width="587" alt="Screen Shot 2020-10-11 at 10 49 38" src="https://user-images.githubusercontent.com/14984911/95674302-8f856b00-0baf-11eb-9b2b-4274279f0990.png">

Maybe there's a third-party extension that affects the coloring?

**Comment by balavishnuvj** [comment]
Oh sorry, was caused by [Babel JavaScript](https://github.com/michaelgmcd/vscode-language-babel). I'm using this for syntax highlighting styled-components. 
Currently, I'm using [Night Owl](https://github.com/sdras/night-owl-vscode-theme). It could highlight so, missed checking whether it was caused by another extension.

**Comment by kettanaito** [comment]
Nice, so the issue is gone once the extension is disabled?

**Comment by balavishnuvj** [comment]
Yup, disabling Babel JavaScript worked with this theme 👍
