### ISSUE TITLE
Low color contrast on auto complete popup

### ISSUE THREAD

**Issue by devrsi0n** [kettanaito/vscode-nako-theme#7]
Thanks for building this awesome theme.
I noticed there is a color contrast issue on auto complete popup.
Can we use a light blue color instead? Thanks for your time.
![image](https://user-images.githubusercontent.com/7880675/126116498-60828c02-b4ea-46e5-85fd-2ae9a7f0d9f8.png)

**Comment by kettanaito** [comment]
Should be fixed by #8.
